name: Windows Build

on:
   workflow_dispatch:
   push:
      branches:
         - main

jobs:
   build:
      runs-on: windows-2022

      steps:
         - name: Checkout
           uses: actions/checkout@v4

         - name: Install Odin
           shell: powershell
           run: |
              Invoke-WebRequest `
                -Uri "https://github.com/odin-lang/Odin/releases/latest/download/odin-windows-amd64.zip" `
                -OutFile "odin.zip"

              Expand-Archive odin.zip -DestinationPath odin

              echo "$PWD\odin" >> $env:GITHUB_PATH

         - name: Build Sniptext
           shell: powershell
           run: |
              odin build src -out:sniptext.exe

         - name: Upload executable
           uses: actions/upload-artifact@v4
           with:
              name: sniptext-windows-x64
              path: sniptext.exe
